### ISSUE TITLE
Some Animations Not Controlled By Trackpad

### ISSUE THREAD

**Issue by kideternal** [Eusth/HoneySelectVR#18]
~20% of the animations can't be started/controlled via trackpad.  Corner masturbation, or dildo usage, for instance.  Weird.

**Comment by Eusth** [comment]
In my experience, these issues might be due to the focus being on the wrong object. At least I've been more succesful after clicking somewhere on the GUI in the menu tool.

The problem seems to be that I'm literally simulating the scrollwheel and the messages fail to arrive where they should.

The clean way to do it would be accessing the speed variable directly. The only problem with that is that the Illusion devs have a different idea of what's clean code and decides to decentralize that part. I'll look into it though.

**Comment by kideternal** [comment]
Yeah, it's definitely focus-related.  I experimented around and if it's not working you can usually get it to work again by toggling a button on/off.

**Comment by kideternal** [comment]
This appears to be fixed. Thanks, Eusth!
