### ISSUE TITLE
New IPA and patching other unity games

### ISSUE THREAD

**Issue by nilslaudrup** [Eusth/HoneySelectVR#40]
Hello Eusth and thank you for all the hard work you have done with these VR-patches!

You wrote on latest release that you can now patch any Unity games with new IPA-beta by dragging the exe file to ipa.exe. I have tried this on couple Unity-based games but I can't get picture to my headset.

When i have dragged the executable to ipa.exe it doesn't give any error and it creates a shortcut with the exe-files name +(patch & launch) . When I launch it, it starts the game but just on my monitor.

Am I doing something wrong? The games that i have tried are Love Raper! School Hamedol Project, Sexaloid girlfriend and Secrossphere.

I would appriciate any help or tips you can give me.

**Comment by Eusth** [comment]
IPA has nothing to do with VR. You just use it to make a Unity game easily moddable.

For VRizing a game, take a look at VRGIN and the manual I made on the wiki. It doesn't work out of the box in many cases, though, because of mismatching Unity versions and dependency issues. Secrossphere and harem mate should work. Love raper probably won't

**Comment by nilslaudrup** [comment]
Thanks for your answer! 

I will take a look at VRGIN and the manual.
